export const initialUsersData = [
  {
    id: 1,
    fullName: 'Admin',
    username: 'admin',
    email: 'admin@gmail.com',
    role: 'Admin',
    status: 'Active',
    createdAt: '29 Jun 2026 03:59 PM',
  },
  {
    id: 2,
    fullName: 'Ezhilmathi',
    username: 'ezhilmathi',
    email: 'ezhil@gmail.com',
    role: 'Cashier',
    status: 'Active',
    createdAt: '29 Jun 2026 04:15 PM',
  },
  {
    id: 3,
    fullName: 'Arulmathi',
    username: 'arulmathi',
    email: 'arul@gmail.com',
    role: 'Manager',
    status: 'Active',
    createdAt: '29 Jun 2026 04:30 PM',
  },
  {
    id: 4,
    fullName: 'Jose',
    username: 'jose',
    email: 'jose@gmail.com',
    role: 'Staff',
    status: 'Active',
    createdAt: '29 Jun 2026 05:00 PM',
  },
  {
    id: 5,
    fullName: 'Yamina',
    username: 'yamina',
    email: 'yamina@gmail.com',
    role: 'Manager',
    status: 'Inactive',
    createdAt: '30 Jun 2026 09:10 AM',
  },
];
