export const inventoryItems = [
  {
    name: 'Black Coffee',
    category: 'Beverage',
    price: '₹15.00',
    unit: 'Cup',
    purchased: 22,
    sold: 22,
    inStock: 0,
    status: 'Out of Stock',
    lastUpdated: '30 Jun 2026, 05:25 PM',
    image: '/menu/black-coffee.png',
  },
  {
    name: 'Black Tea',
    category: 'Beverage',
    price: '₹20.00',
    unit: 'Cup',
    purchased: 15,
    sold: 2,
    inStock: 13,
    status: 'In Stock',
    lastUpdated: '30 Jun 2026, 11:18 AM',
    image: '/menu/black-tea.png',
  },
  {
    name: 'Bubble Tea',
    category: 'Beverage',
    price: '₹80.00',
    unit: 'Cup',
    purchased: 14,
    sold: 9,
    inStock: 5,
    status: 'Low Stock',
    lastUpdated: '30 Jun 2026, 06:24 PM',
    image: '/menu/bubble-tea.png',
  },
  {
    name: 'Ginger Tea',
    category: 'Beverage',
    price: '₹24.00',
    unit: 'Cup',
    purchased: 15,
    sold: 3,
    inStock: 12,
    status: 'In Stock',
    lastUpdated: '29 Jun 2026, 09:02 PM',
    image: '/menu/ginger-tea.png',
  },
  {
    name: 'Cold Coffee',
    category: 'Beverage',
    price: '₹20.00',
    unit: 'Cup',
    purchased: 18,
    sold: 5,
    inStock: 13,
    status: 'In Stock',
    lastUpdated: '30 Jun 2026, 08:10 PM',
    image: '/menu/cold-coffee.png',
  },
  {
    name: 'Iced Tea',
    category: 'Beverage',
    price: '₹50.00',
    unit: 'Cup',
    purchased: 20,
    sold: 6,
    inStock: 14,
    status: 'In Stock',
    lastUpdated: '30 Jun 2026, 07:30 PM',
    image: '/menu/iced-tea.png',
  },
  {
    name: 'Milk',
    category: 'Beverage',
    price: '₹20.00',
    unit: 'Cup',
    purchased: 12,
    sold: 7,
    inStock: 5,
    status: 'Low Stock',
    lastUpdated: '01 Jul 2026, 09:49 AM',
    image: '/menu/milk.png',
  },
  {
    name: 'Milo',
    category: 'Beverage',
    price: '₹60.00',
    unit: 'Cup',
    purchased: 32,
    sold: 4,
    inStock: 28,
    status: 'In Stock',
    lastUpdated: '01 Jul 2026, 09:49 AM',
    image: '/menu/milo.png',
  },
  {
    name: 'Masala Tea',
    category: 'Beverage',
    price: '₹30.00',
    unit: 'Cup',
    purchased: 18,
    sold: 18,
    inStock: 0,
    status: 'Out of Stock',
    lastUpdated: '30 Jun 2026, 10:12 PM',
    image: '/menu/ginger-tea.png',
  },
  {
    name: 'Lemon Tea',
    category: 'Beverage',
    price: '₹35.00',
    unit: 'Cup',
    purchased: 16,
    sold: 8,
    inStock: 8,
    status: 'In Stock',
    lastUpdated: '01 Jul 2026, 10:04 AM',
    image: '/menu/iced-tea.png',
  },
];
