export const itemRequests = [
  {
    id: 'REQ-000001',
    subject: 'Request for Black Tea',
    requestedBy: 'Admin',
    requestedDate: '29 Jun 2026',
    requestedTime: '10:15 AM',
    expectedDelivery: '30 Jun 2026',
    status: 'Received',
  },
  {
    id: 'REQ-000002',
    subject: 'Request for Bubble Tea',
    requestedBy: 'Jose',
    requestedDate: '29 Jun 2026',
    requestedTime: '12:06 PM',
    expectedDelivery: '30 Jun 2026',
    status: 'Pending',
  },
  {
    id: 'REQ-000003',
    subject: 'Request for Iced Tea',
    requestedBy: 'Admin',
    requestedDate: '29 Jun 2026',
    requestedTime: '03:44 PM',
    expectedDelivery: '01 Jul 2026',
    status: 'On The Way',
  },
  {
    id: 'REQ-000004',
    subject: 'Request for Ginger Tea',
    requestedBy: 'Admin',
    requestedDate: '30 Jun 2026',
    requestedTime: '09:55 AM',
    expectedDelivery: '01 Jul 2026',
    status: 'Cancelled',
  },
  {
    id: 'REQ-000005',
    subject: 'Request for Milk',
    requestedBy: 'Admin',
    requestedDate: '30 Jun 2026',
    requestedTime: '01:26 AM',
    expectedDelivery: '01 Jul 2026',
    status: 'Received',
  },
  {
    id: 'REQ-000006',
    subject: 'Request for Milk',
    requestedBy: 'Admin',
    requestedDate: '30 Jun 2026',
    requestedTime: '01:31 AM',
    expectedDelivery: '30 Jun 2026',
    status: 'Received',
  },
  {
    id: 'REQ-000007',
    subject: 'Request for Milo',
    requestedBy: 'Jose',
    requestedDate: '30 Jun 2026',
    requestedTime: '09:32 AM',
    expectedDelivery: '01 Jul 2026',
    status: 'Received',
  },
  {
    id: 'REQ-000008',
    subject: 'Request for Bubble Tea',
    requestedBy: 'Jose',
    requestedDate: '30 Jun 2026',
    requestedTime: '09:36 AM',
    expectedDelivery: '02 Jul 2026',
    status: 'Cancelled',
  },
  {
    id: 'REQ-000009',
    subject: 'Request for Black Coffee',
    requestedBy: 'Admin',
    requestedDate: '30 Jun 2026',
    requestedTime: '07:47 PM',
    expectedDelivery: '03 Jul 2026',
    status: 'Pending',
  },
  {
    id: 'REQ-000010',
    subject: 'Request for Black Coffee',
    requestedBy: 'Admin',
    requestedDate: '01 Jul 2026',
    requestedTime: '08:43 PM',
    expectedDelivery: '03 Jul 2026',
    status: 'On The Way',
  },
];
